import type { Topic } from '../types'

export const databaseTopics: Topic[] = [
  {
    id: 'acid-transactions', roadmap: 'database', tier: 1,
    title: 'Transactions and ACID',
    summary: 'The unit of atomic work, and what each of the four letters actually promises.',
    whyItMatters: 'Every correctness argument in a backend service eventually reduces to a transaction boundary. ACID is not trivia — it is the contract the rest of your reasoning depends on.',
    whatToLearn: [
      'Atomicity: all or nothing, and how rollback delivers it',
      'Consistency as constraint preservation — not the distributed-systems meaning of the word',
      'Isolation as the hardest and most configurable of the four',
      'Durability, and why it means a write-ahead log rather than a flush to the table',
      'Where a transaction should begin and end in a service',
    ],
    dependencies: [],
    nextSteps: [{ roadmap: 'database', topic: 'isolation-levels' }, { roadmap: 'spring', topic: 'transactional-deep' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Which letter of ACID is negotiable in practice?', expects: 'Isolation — it is the one with configurable levels, and relaxing it is a deliberate performance trade.' },
      { q: 'How does the database survive a crash mid-commit?', expects: 'Write-ahead logging: the log is durable before the data pages, so recovery can redo or undo.' },
    ],
    systemContext: 'The transaction boundary is the line a service designer draws around "must be consistent". Everything outside it needs a different guarantee.',
    related: [{ to: { roadmap: 'spring', topic: 'transactional-deep' }, kind: 'implements', why: '@Transactional is this primitive exposed declaratively — its limits are these limits.' }],
  },
  {
    id: 'isolation-levels', roadmap: 'database', tier: 2,
    title: 'Isolation levels and read anomalies',
    summary: 'Dirty read, non-repeatable read, phantom, lost update — and which level prevents which.',
    whyItMatters: 'Picking an isolation level is choosing which anomalies you accept in exchange for throughput. Doing it without knowing the anomalies is choosing blind.',
    whatToLearn: [
      'The four anomalies, each with a concrete two-transaction interleaving',
      'READ UNCOMMITTED / READ COMMITTED / REPEATABLE READ / SERIALIZABLE',
      'Lost update — often missed because it is not in the original SQL standard list',
      'Why the same level behaves differently across engines',
      'Optimistic versioning as an application-level alternative',
    ],
    dependencies: [{ roadmap: 'database', topic: 'acid-transactions' }],
    nextSteps: [{ roadmap: 'database', topic: 'mvcc' }, { roadmap: 'database', topic: 'locking' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Give me a concrete interleaving that produces a non-repeatable read.', expects: 'Two reads of the same row in T1 with a committed update from T2 in between — stated as an actual sequence, not a definition.' },
      { q: 'PostgreSQL REPEATABLE READ vs MySQL REPEATABLE READ — same thing?', expects: 'No. PostgreSQL prevents phantoms at that level via snapshot isolation; MySQL InnoDB uses next-key locks. Same name, different guarantees.' },
      { q: 'Two users decrement the same stock count. What goes wrong and how do you fix it?', expects: 'Lost update. Fixed by SELECT FOR UPDATE, an atomic UPDATE with a guard, or optimistic versioning — each with a different contention profile.' },
    ],
    systemContext: 'The isolation attribute on @Transactional is delegated straight here. Choosing it is a database decision that Spring only forwards.',
    related: [
      { to: { roadmap: 'spring', topic: 'transactional-deep' }, kind: 'implements', why: 'The isolation attribute in Spring resolves to exactly these levels — Spring implements none of it.' },
      { to: { roadmap: 'database', topic: 'mvcc' }, kind: 'requires', why: 'On PostgreSQL and Oracle these levels are delivered by snapshot visibility rather than by read locks.' },
      { to: { roadmap: 'java', topic: 'threads-and-safety' }, kind: 'contrasts', why: 'Lost update is the database\'s version of the lost-increment race — same problem, solved at storage rather than in the JVM.' },
    ],
  },
  {
    id: 'mvcc', roadmap: 'database', tier: 2,
    title: 'MVCC — multi-version concurrency control',
    summary: 'Readers see a snapshot, writers create new versions, and neither blocks the other.',
    whyItMatters: 'MVCC is why a modern database can serve consistent reads under heavy write load without a reader ever waiting on a writer. It is the mechanism behind the isolation level you selected.',
    whatToLearn: [
      'Row versions with visibility metadata rather than in-place overwrite',
      'Snapshots: a transaction sees a consistent point-in-time view',
      'Readers do not block writers, writers do not block readers — writers still block writers',
      'Version accumulation, and why vacuum or undo cleanup exists',
      'Long-running transactions holding back cleanup and bloating storage',
    ],
    dependencies: [{ roadmap: 'database', topic: 'isolation-levels' }],
    nextSteps: [{ roadmap: 'database', topic: 'locking' }, { roadmap: 'database', topic: 'query-execution' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Under MVCC, does a long read block a write?', expects: 'No. The reader has a snapshot; the writer creates a new version. The cost shows up as version accumulation, not as blocking.' },
      { q: 'What is the operational danger of a very long transaction?', expects: 'It pins a snapshot, so old versions cannot be cleaned. Storage grows and scans slow down — bloat, not blocking.' },
      { q: 'How does MVCC deliver REPEATABLE READ?', expects: 'The snapshot is taken once and reused for the whole transaction, so repeated reads see identical data by construction.' },
    ],
    systemContext: 'This is the layer at which "why is my read consistent but my disk filling up" gets answered — a question that only makes sense once you know reads are served from versions.',
    related: [
      { to: { roadmap: 'spring', topic: 'transactional-deep' }, kind: 'implements', why: 'When you request REPEATABLE_READ in Spring on PostgreSQL, this snapshot mechanism is what actually delivers it.' },
      { to: { roadmap: 'database', topic: 'locking' }, kind: 'contrasts', why: 'MVCC removes read-write blocking; locking is still required for write-write conflicts.' },
      { to: { roadmap: 'hld', topic: 'consistency' }, kind: 'contrasts', why: 'Single-node snapshot consistency and distributed consistency share vocabulary and almost nothing else.' },
    ],
  },
  {
    id: 'locking', roadmap: 'database', tier: 2,
    title: 'Locking, deadlocks and concurrency control',
    summary: 'Shared and exclusive locks, optimistic versus pessimistic, and how deadlocks are detected.',
    whyItMatters: 'Write-write conflicts still need locks even under MVCC. Choosing optimistic or pessimistic is a contention decision with real throughput consequences.',
    whatToLearn: [
      'Shared vs exclusive, and lock granularity from row to table',
      'SELECT FOR UPDATE as explicit pessimistic locking',
      'Optimistic concurrency with a version column, and handling the retry',
      'Deadlock detection, victim selection, and designing for retry',
      'Lock ordering as prevention — the same rule as in the JVM',
    ],
    dependencies: [{ roadmap: 'database', topic: 'mvcc' }],
    nextSteps: [{ roadmap: 'database', topic: 'query-execution' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Optimistic or pessimistic for a seat-booking system?', expects: 'A defensible answer either way — pessimistic under high contention for the same rows, optimistic when conflicts are rare and retries cheap.' },
      { q: 'Your transaction was chosen as a deadlock victim. What should the application do?', expects: 'Catch it and retry with backoff — deadlocks are expected under concurrency, not exceptional.' },
    ],
    related: [{ to: { roadmap: 'java', topic: 'threads-and-safety' }, kind: 'contrasts', why: 'Lock ordering prevents deadlock identically here and in the JVM; only the resources differ.' }],
  },
  {
    id: 'indexes', roadmap: 'database', tier: 2,
    title: 'Indexes — B-tree, composite, selectivity',
    summary: 'How an index turns a scan into a seek, and why the wrong column order makes it useless.',
    whyItMatters: 'Index design is the highest-leverage database skill. Most slow queries are one index away, and most redundant indexes are silently taxing every write.',
    whatToLearn: [
      'B+ tree structure and why it suits range queries and sorted access',
      'Composite index column order, and the leftmost-prefix rule',
      'Selectivity and cardinality — why an index on a boolean rarely helps',
      'Covering indexes and index-only scans',
      'The write cost: every index is maintained on insert, update and delete',
    ],
    dependencies: [{ roadmap: 'database', topic: 'acid-transactions' }],
    nextSteps: [{ roadmap: 'database', topic: 'query-execution' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'You have an index on (a, b). Which of these use it: WHERE a=1, WHERE b=2, WHERE a=1 AND b=2?', expects: 'First and third. The second cannot — leftmost prefix. Explaining why in terms of tree ordering is the strong answer.' },
      { q: 'When does adding an index make things worse?', expects: 'Write-heavy tables, low-selectivity columns, and redundant indexes that duplicate an existing prefix.' },
    ],
    systemContext: 'A Spring Data derived query method compiles to SQL that either uses an index or scans. The abstraction does not remove the decision, it hides it.',
    related: [{ to: { roadmap: 'spring', topic: 'jpa-basics' }, kind: 'requires', why: 'Repository methods generate SQL whose performance is entirely determined by indexing.' }],
  },
  {
    id: 'query-execution', roadmap: 'database', tier: 2,
    title: 'Query execution and the optimizer',
    summary: 'Parse, rewrite, plan, execute — and how to read what the optimizer chose.',
    whyItMatters: 'Reading a plan is the difference between guessing at performance and diagnosing it. This is also the layer your Oracle experience sits in.',
    whatToLearn: [
      'The pipeline: parse, semantic analysis, rewrite, optimize, execute',
      'Cost-based optimization, and statistics as its input',
      'Access paths: sequential scan, index scan, index-only scan',
      'Join strategies: nested loop, hash join, merge join, and when each wins',
      'Reading EXPLAIN ANALYZE — estimated versus actual rows as the key signal',
      'Why stale statistics produce catastrophically wrong plans',
    ],
    dependencies: [{ roadmap: 'database', topic: 'indexes' }],
    nextSteps: [{ roadmap: 'database', topic: 'vector-indexing' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'EXPLAIN estimates 10 rows, the query returns 400,000. What does that tell you?', expects: 'Stale or insufficient statistics. The plan was chosen for the wrong shape — likely a nested loop where a hash join was needed.' },
      { q: 'When is a sequential scan the right plan?', expects: 'When a large fraction of the table is needed — random index lookups then cost more than reading sequentially.' },
    ],
    systemContext: 'This is precisely the layer of Oracle RDBMS work on the experience page: parser, transformation, plan analysis, access-path selection.',
    related: [{ to: { roadmap: 'spring', topic: 'persistence-context' }, kind: 'requires', why: 'Fixing N+1 with a fetch join produces one large query whose plan has to be read here.' }],
  },
  {
    id: 'vector-indexing', roadmap: 'database', tier: 3,
    title: 'Vector indexing — HNSW and IVF',
    summary: 'Approximate nearest neighbour search, and the recall-versus-latency trade that defines it.',
    whyItMatters: 'Vector search is exact search giving up guarantees for speed. The whole engineering problem is quantifying what you gave up.',
    whatToLearn: [
      'Why exact nearest-neighbour does not scale, and what approximation buys',
      'HNSW: navigable small-world graphs, and the ef/M parameters',
      'IVF: partition into cells, probe a subset, and the nprobe trade',
      'recall@k as the accuracy measure, and why latency alone is meaningless without it',
      'Building a parameter sweep that makes the trade-off visible',
    ],
    dependencies: [{ roadmap: 'database', topic: 'query-execution' }],
    nextSteps: [],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Your vector search got 3x faster. What do you check before celebrating?', expects: 'recall@k. Speed at unknown accuracy is not a result — approximate search can always be made faster by being more wrong.' },
      { q: 'HNSW or IVF?', expects: 'HNSW for low latency and high recall at higher memory; IVF for large corpora where memory dominates. The answer is a trade-off, not a winner.' },
    ],
    systemContext: 'This is the substance of the vector-search benchmarking work on the experience page — a parameterized sweep across HNSW and IVF configurations measuring recall and latency at billion-row scale.',
    related: [{ to: { roadmap: 'database', topic: 'indexes' }, kind: 'contrasts', why: 'A B-tree gives exact answers with guaranteed bounds; a vector index trades that guarantee for tractable high-dimensional search.' }],
  },
]
