import type { Topic } from '../types'

export const hldTopics: Topic[] = [
  {
    id: 'latency', roadmap: 'hld', tier: 1,
    title: 'Latency, throughput and tail behaviour',
    summary: 'The non-functional requirements that decide every other choice in a design.',
    whyItMatters: 'A design without numbers is a drawing. Latency and throughput targets are what make one architecture correct and another wasteful.',
    whatToLearn: [
      'Latency vs throughput — improving one often costs the other',
      'Why p99 matters more than average, and what a fan-out does to it',
      'Order-of-magnitude numbers: memory, SSD, same-datacentre, cross-region',
      'Where queueing turns a small slowdown into a collapse',
    ],
    dependencies: [],
    nextSteps: [{ roadmap: 'hld', topic: 'concurrency-scaling' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'A request fans out to 10 services each with a 1% slow tail. What is your tail?', expects: 'Roughly 1 − 0.99^10 ≈ 10% — fan-out amplifies tail latency, which is the argument for hedging or reducing fan-out.' },
    ],
    systemContext: 'A p99 target is enforced or broken by GC pauses, pool saturation and downstream tails — the JVM roadmap connects directly here.',
    related: [{ to: { roadmap: 'java', topic: 'gc' }, kind: 'requires', why: 'Collector pauses are a direct contributor to the tail this topic budgets for.' }],
  },
  {
    id: 'concurrency-scaling', roadmap: 'hld', tier: 1,
    title: 'Concurrency and horizontal scaling',
    summary: 'How many requests one instance can hold, and what that implies for instance count.',
    whyItMatters: 'Capacity estimation is arithmetic over per-instance concurrency. Without it, "we will scale horizontally" is a hope rather than a plan.',
    whatToLearn: [
      'Vertical vs horizontal scaling, and where each stops working',
      'Per-instance concurrency as a function of thread pool and downstream service time',
      'Statelessness as the precondition for horizontal scaling',
      "Little's Law: concurrency = arrival rate × service time",
      'The database as the shared bottleneck that horizontal scaling does not fix',
    ],
    dependencies: [{ roadmap: 'hld', topic: 'latency' }],
    nextSteps: [{ roadmap: 'hld', topic: 'message-queue' }, { roadmap: 'hld', topic: 'backpressure' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: '1,000 requests/second, 200ms service time. How much concurrency do you need?', expects: '200 in flight by Little\'s Law, then divided by per-instance pool capacity to get instance count.' },
      { q: 'You doubled your instances and throughput barely moved. Where do you look?', expects: 'The shared dependency — connection pool limits or the database itself. Horizontal scaling multiplies pressure on it.' },
    ],
    systemContext: 'Per-instance capacity is literally the thread pool configuration from the Java roadmap. This is the same number viewed from the architecture level.',
    related: [
      { to: { roadmap: 'java', topic: 'executor-service' }, kind: 'requires', why: 'Per-instance concurrency is decided by pool sizing — the capacity plan is that configuration multiplied by instance count.' },
      { to: { roadmap: 'spring', topic: 'async' }, kind: 'requires', why: 'Async offloading changes per-instance capacity, so it changes the estimate.' },
    ],
  },
  {
    id: 'message-queue', roadmap: 'hld', tier: 2,
    title: 'Message queues and event-driven architecture',
    summary: 'Decoupling producers from consumers, and the guarantees that come with it.',
    whyItMatters: 'Async messaging is how a system absorbs load spikes and survives partial failure — at the cost of eventual consistency and duplicate delivery.',
    whatToLearn: [
      'Decoupling in time, in failure, and in throughput',
      'At-most-once, at-least-once, exactly-once — and why the last is mostly a lie',
      'Partitioning and ordering guarantees within a partition',
      'Consumer groups and rebalancing',
      'Retry, DLQ, and poison-message handling',
    ],
    dependencies: [{ roadmap: 'hld', topic: 'concurrency-scaling' }],
    nextSteps: [{ roadmap: 'hld', topic: 'idempotency' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Kafka guarantees ordering. Under what condition?', expects: 'Within a partition only. Global ordering requires one partition, which forfeits parallelism.' },
      { q: 'When is a queue the wrong choice?', expects: 'When the caller needs a synchronous answer, or when eventual consistency is unacceptable to the domain.' },
    ],
    systemContext: 'OrderFlow uses exactly this: Kafka between the order service and four consumers, with retry and DLQ on the failure path.',
    related: [
      { to: { roadmap: 'spring', topic: 'outbox' }, kind: 'requires', why: 'Reliable publishing into the queue is the outbox\'s job — without it the architecture loses events.' },
      { to: { roadmap: 'java', topic: 'concurrent-collections' }, kind: 'contrasts', why: 'A BlockingQueue is the same idea inside one JVM, which is why it cannot survive a restart.' },
    ],
  },
  {
    id: 'idempotency', roadmap: 'hld', tier: 2,
    title: 'Idempotency and retry safety',
    summary: 'Making repeated delivery harmless, because at-least-once guarantees repetition.',
    whyItMatters: 'Once a transaction cannot span the boundary, idempotency is the guarantee that replaces it. Every retry policy assumes it.',
    whatToLearn: [
      'Idempotency keys supplied by the client',
      'Natural idempotency through upsert and conditional update',
      'Deduplication tables, and their retention problem',
      'Why retries without idempotency turn a timeout into double-charging',
      'Idempotency at the API layer versus at the consumer',
    ],
    dependencies: [{ roadmap: 'hld', topic: 'message-queue' }],
    nextSteps: [],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'A payment request times out. Is it safe to retry?', expects: 'Only with an idempotency key — the timeout says nothing about whether the server processed it.' },
      { q: 'Where do you deduplicate: API or consumer?', expects: 'Both, for different reasons — the API protects against client retries, the consumer against broker redelivery.' },
    ],
    systemContext: 'In OrderFlow, consumers deduplicate on event id precisely because the outbox relay guarantees at-least-once.',
    related: [
      { to: { roadmap: 'spring', topic: 'transactional-deep' }, kind: 'contrasts', why: 'Where a transaction cannot reach, idempotency substitutes retry safety for atomicity.' },
      { to: { roadmap: 'spring', topic: 'outbox' }, kind: 'requires', why: 'The outbox produces duplicates by design; idempotent consumers are what make that acceptable.' },
    ],
  },
  {
    id: 'backpressure', roadmap: 'hld', tier: 2,
    title: 'Backpressure and load shedding',
    summary: 'Failing fast on purpose, because an unbounded queue is a slow outage.',
    whyItMatters: 'Systems without backpressure do not degrade — they collapse. Bounding and shedding are how a service stays alive under more load than it can serve.',
    whatToLearn: [
      'Bounded queues everywhere; unbounded is deferred failure',
      'Load shedding, and why rejecting early beats timing out late',
      'Circuit breakers to stop hammering a failing dependency',
      'Rate limiting at the edge',
      'Timeouts as the precondition for every other resilience mechanism',
    ],
    dependencies: [{ roadmap: 'hld', topic: 'concurrency-scaling' }],
    nextSteps: [],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Why is an unbounded queue dangerous?', expects: 'It converts overload into memory growth and rising latency, so the system fails later and worse than if it had rejected work.' },
    ],
    systemContext: 'A bounded thread pool with an abort policy is backpressure inside one process; a rate limiter is the same idea at the edge.',
    related: [{ to: { roadmap: 'java', topic: 'executor-service' }, kind: 'implements', why: 'Bounded queue plus rejection policy is this principle implemented in a single JVM.' }],
  },
  {
    id: 'api-design', roadmap: 'hld', tier: 2,
    title: 'API design and contracts',
    summary: 'Resources, versioning, pagination, and the error semantics callers build retries on.',
    whyItMatters: 'The contract outlives the implementation. Status codes and pagination decisions are load-bearing for every consumer.',
    whatToLearn: [
      'Resource modelling and predictable URI structure',
      'Cursor vs offset pagination, and why offset breaks at scale',
      'Versioning strategies and their migration cost',
      'Error semantics that distinguish retryable from terminal',
      'Timeouts and client-side deadlines as part of the contract',
    ],
    dependencies: [{ roadmap: 'hld', topic: 'latency' }],
    nextSteps: [{ roadmap: 'hld', topic: 'idempotency' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Why does offset pagination break on large datasets?', expects: 'The database still scans and discards the offset rows, so cost grows with page number — and concurrent inserts shift the window.' },
    ],
    related: [{ to: { roadmap: 'spring', topic: 'rest-api' }, kind: 'implements', why: 'The contract designed here is what the controller layer implements.' }],
  },
  {
    id: 'consistency', roadmap: 'hld', tier: 2,
    title: 'Consistency, replication and CAP',
    summary: 'What you give up when data lives in more than one place.',
    whyItMatters: 'Replication is how systems get availability and read scale, and consistency is the bill. Knowing which reads can tolerate staleness is a design decision, not a database setting.',
    whatToLearn: [
      'Strong vs eventual consistency, stated in terms of what a client can observe',
      'Leader-follower replication and replica lag',
      'Read-your-writes as the guarantee users actually notice',
      'CAP as a statement about partitions, not a menu of two',
      'Choosing per-read: which queries may serve stale data',
    ],
    dependencies: [{ roadmap: 'hld', topic: 'message-queue' }],
    nextSteps: [],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'A user updates their profile then immediately reloads and sees the old value. What happened and how do you fix it?', expects: 'Replica lag with a read routed to a follower. Fixed by routing that user\'s reads to the leader for a window, or by read-your-writes tracking.' },
    ],
    related: [{ to: { roadmap: 'database', topic: 'mvcc' }, kind: 'contrasts', why: 'Snapshot consistency on one node and consistency across replicas share vocabulary but solve different problems.' }],
  },
]
