import type { Topic } from '../types'

/** Java — Tier 2. Internals and concurrency: the depth an SDE-2 loop probes. */
export const javaTier2: Topic[] = [
  {
    id: 'hashmap-internals', roadmap: 'java', tier: 2,
    title: 'HashMap internals',
    summary: 'Buckets, collisions, resize, and the treeification threshold.',
    whyItMatters: 'The most-asked Java internals question, and the one that proves you have read the JDK rather than only used it.',
    whatToLearn: [
      'Bucket array, index derivation, and why capacity is a power of two',
      'Collision handling: chaining, then treeification at 8 nodes per bucket',
      'Load factor 0.75, resize doubling, and rehash cost',
      'Why a poor hashCode degrades lookup toward O(n) — or O(log n) after treeification',
      'Fail-fast iteration and ConcurrentModificationException',
    ],
    dependencies: [{ roadmap: 'java', topic: 'equals-hashcode' }, { roadmap: 'java', topic: 'collections' }],
    nextSteps: [{ roadmap: 'java', topic: 'concurrent-collections' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Walk me through what happens on put when the bucket is occupied.', expects: 'Hash, index, traverse the chain comparing with equals, replace or append, then check the treeify threshold and the resize threshold.' },
      { q: 'Why is the capacity always a power of two?', expects: 'It lets index derivation use a bitmask instead of modulo, and keeps rehash-on-resize cheap.' },
      { q: 'What breaks if two threads put concurrently?', expects: 'Lost updates, and in older JDKs an infinite loop during concurrent resize. The fix is ConcurrentHashMap, not synchronizing every call.' },
    ],
    systemContext: 'An in-memory cache built on HashMap under concurrent load is a real production incident pattern — it usually surfaces as a pinned CPU core rather than an exception.',
    related: [
      { to: { roadmap: 'java', topic: 'concurrent-collections' }, kind: 'contrasts', why: 'ConcurrentHashMap solves the same lookup problem with per-bin locking, trading memory and complexity for safe concurrent access.' },
      { to: { roadmap: 'dsa', topic: 'hashing' }, kind: 'implements', why: 'Every hash-based DSA pattern assumes exactly these mechanics underneath.' },
    ],
    practice: {
      intent: 'Make the internals observable.',
      exercises: [
        { title: 'Force every collision', detail: 'Write a key whose hashCode always returns 1. Insert 10,000 of them and time lookup against a well-distributed key. Explain the curve, including where treeification changes it.' },
        { title: 'Break it concurrently', detail: 'Have ten threads put into a shared HashMap. Compare final size against expected. Then swap in ConcurrentHashMap and compare again.' },
      ],
    },
  },
  {
    id: 'jvm-memory', roadmap: 'java', tier: 2,
    title: 'JVM memory — heap, stack, metaspace',
    summary: 'Where objects live, where references live, and what actually causes each kind of OutOfMemoryError.',
    whyItMatters: 'You cannot diagnose a memory incident without a model of the regions. The distinction between a heap OOM and a metaspace OOM points at completely different causes.',
    whatToLearn: [
      'Stack per thread, heap shared; what that means for escaping references',
      'Young generation, old generation, and promotion',
      'Metaspace and class metadata — and why it is off-heap since Java 8',
      'Reference strength: strong, soft, weak, phantom',
      'Reading the difference between OutOfMemoryError: Java heap space and Metaspace',
    ],
    dependencies: [{ roadmap: 'java', topic: 'platform' }],
    nextSteps: [{ roadmap: 'java', topic: 'gc' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Heap OOM versus metaspace OOM — what causes each?', expects: 'Heap: object retention, usually an unbounded cache or collection. Metaspace: class leakage, usually dynamic proxies or repeated redeploys in one JVM.' },
      { q: 'Where does a local variable holding an object reference live?', expects: 'The reference on the stack, the object on the heap — and why that distinction drives escape analysis.' },
    ],
    systemContext: 'Container memory limits are set against the whole process, not the heap. A -Xmx equal to the container limit gets the JVM OOM-killed, because metaspace, thread stacks and native buffers live outside it.',
    related: [{ to: { roadmap: 'java', topic: 'gc' }, kind: 'enables', why: 'Collector behaviour only makes sense once you know which region it is collecting.' }],
  },
  {
    id: 'gc', roadmap: 'java', tier: 2,
    title: 'Garbage collection',
    summary: 'Reachability, generational collection, and what a pause actually costs a request.',
    whyItMatters: 'GC is the usual suspect behind unexplained p99 latency. Knowing which collector you are running, and why, is a production skill.',
    whatToLearn: [
      'Reachability from GC roots — not reference counting',
      'Why generational collection works: most objects die young',
      'Minor vs major collection, and stop-the-world pauses',
      'G1 as the modern default; where ZGC and Shenandoah change the trade-off',
      'Reading GC logs and correlating pauses with latency spikes',
    ],
    dependencies: [{ roadmap: 'java', topic: 'jvm-memory' }],
    nextSteps: [{ roadmap: 'hld', topic: 'latency' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Your p99 latency spikes every few minutes but p50 is flat. Where do you look?', expects: 'GC logs first — the shape is characteristic of stop-the-world pauses, not of slow code.' },
      { q: 'Can you force garbage collection?', expects: 'No. System.gc() is a suggestion, and calling it in application code is a smell.' },
    ],
    systemContext: 'A latency SLO is a GC configuration decision as much as an application one. This is the layer where JVM tuning meets the non-functional requirement.',
    related: [{ to: { roadmap: 'hld', topic: 'latency' }, kind: 'implements', why: 'Tail latency targets in a system design are enforced, or broken, by collector choice at this layer.' }],
  },
  {
    id: 'threads-and-safety', roadmap: 'java', tier: 2,
    title: 'Threads, race conditions and the memory model',
    summary: 'Why shared mutable state breaks, and what synchronized and volatile each actually guarantee.',
    whyItMatters: 'Concurrency bugs do not fail loudly. They corrupt state under load and disappear when you attach a debugger. This is the foundation for everything above it.',
    whatToLearn: [
      'Race condition vs data race — related but not the same',
      'Atomicity, visibility, ordering: the three things the memory model governs',
      'synchronized — mutual exclusion AND a happens-before edge',
      'volatile — visibility and ordering, but no atomicity',
      'Why i++ is three operations, and why volatile does not fix it',
      'Deadlock: the four conditions and lock ordering as the practical defence',
    ],
    dependencies: [{ roadmap: 'java', topic: 'oop' }],
    nextSteps: [{ roadmap: 'java', topic: 'executor-service' }, { roadmap: 'java', topic: 'concurrent-collections' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Does volatile make count++ thread-safe?', expects: 'No — read-modify-write is not atomic. volatile fixes visibility only; you need an atomic or a lock.' },
      { q: 'Two threads, two locks, acquired in different orders. What happens and how do you prevent it?', expects: 'Deadlock, prevented by a global lock ordering or by tryLock with a timeout.' },
      { q: 'How would you find a deadlock in production?', expects: 'Thread dump, look for BLOCKED threads and the cyclic ownership the JVM reports.' },
    ],
    systemContext: 'A Spring singleton bean is shared across every request thread. Any mutable field on it is a data race in a live service — this is the most common accidental concurrency bug in Spring applications.',
    related: [
      { to: { roadmap: 'spring', topic: 'bean-scopes' }, kind: 'implements', why: 'Singleton scope is exactly the shared-mutable-state situation this topic describes, created by the framework on your behalf.' },
      { to: { roadmap: 'database', topic: 'isolation-levels' }, kind: 'contrasts', why: 'A database solves the same lost-update problem at the storage layer with isolation and locking rather than with JVM monitors.' },
    ],
    practice: {
      intent: 'Reproduce a race, then fix it three different ways and compare.',
      exercises: [
        { title: 'Lose increments on purpose', detail: 'Ten threads, 10,000 increments each, on a plain int. Show the final count is under 100,000. Explain exactly which operation was lost.' },
        { title: 'Three fixes, one problem', detail: 'Fix the counter with synchronized, then ReentrantLock, then AtomicInteger. Benchmark all three under contention and explain the ordering of the results.' },
        { title: 'Build and diagnose a deadlock', detail: 'Write a two-lock deadlock, trigger it, take a thread dump with jstack, and point at the cycle in the output.' },
      ],
    },
  },
  {
    id: 'concurrent-collections', roadmap: 'java', tier: 2,
    title: 'Concurrent collections',
    summary: 'ConcurrentHashMap, BlockingQueue, CopyOnWriteArrayList — and when each earns its cost.',
    whyItMatters: 'Wrapping a HashMap in synchronized serialises every access. The concurrent collections exist because that is usually the wrong trade.',
    whatToLearn: [
      'ConcurrentHashMap: per-bin locking, and why size() is an estimate',
      'computeIfAbsent as an atomic operation, not a convenience',
      'BlockingQueue as the backbone of producer-consumer',
      'CopyOnWriteArrayList: read-heavy, write-rare only',
      'Why Collections.synchronizedMap is not a substitute',
    ],
    dependencies: [{ roadmap: 'java', topic: 'hashmap-internals' }, { roadmap: 'java', topic: 'threads-and-safety' }],
    nextSteps: [{ roadmap: 'java', topic: 'executor-service' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'ConcurrentHashMap vs Collections.synchronizedMap?', expects: 'Lock granularity — one lock for the whole map versus per-bin locking, and the throughput difference under contention.' },
      { q: 'Is get-then-put on a ConcurrentHashMap thread-safe?', expects: 'No. Each call is atomic, the sequence is not. Use computeIfAbsent or putIfAbsent.' },
    ],
    systemContext: 'A BlockingQueue between an ingest thread and a pool of workers is the in-process version of the queue you would draw in a system design.',
    related: [{ to: { roadmap: 'hld', topic: 'message-queue' }, kind: 'implements', why: 'A BlockingQueue is the same decoupling idea as Kafka, bounded to one JVM — which is precisely why it does not survive a restart.' }],
    practice: {
      intent: 'Get the atomicity boundary right.',
      exercises: [
        { title: 'The compound-operation bug', detail: 'Build a concurrent counter map with get-then-put across threads and show lost updates. Fix with merge or compute.' },
        { title: 'Producer-consumer', detail: 'One producer, three consumers, bounded BlockingQueue. Demonstrate backpressure by making consumers slower than the producer.' },
      ],
    },
  },
  {
    id: 'executor-service', roadmap: 'java', tier: 2,
    title: 'ExecutorService and thread pools',
    summary: 'Decoupling task submission from thread management — and the queue/pool sizing that decides how your service behaves under load.',
    whyItMatters: 'Every asynchronous feature in a backend service sits on a pool. Pool and queue configuration is where "it worked in staging" becomes an outage: the defaults silently choose either unbounded memory growth or dropped work.',
    whatToLearn: [
      'Runnable vs Callable, and Future as the handle to a pending result',
      'ThreadPoolExecutor parameters: core size, max size, keep-alive, queue, rejection policy',
      'The counter-intuitive rule: an unbounded queue means max pool size is never reached',
      'Sizing: CPU-bound near core count, IO-bound far higher — and why',
      'Rejection policies, and why AbortPolicy is usually more honest than CallerRuns',
      'Always shut down: shutdown vs shutdownNow, and awaitTermination',
      'CompletableFuture for composing async work without blocking on get()',
    ],
    dependencies: [{ roadmap: 'java', topic: 'threads-and-safety' }, { roadmap: 'java', topic: 'concurrent-collections' }],
    nextSteps: [{ roadmap: 'spring', topic: 'async' }, { roadmap: 'java', topic: 'advanced-concurrency' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'You configure core 5, max 50, with an unbounded LinkedBlockingQueue. When does the pool grow to 50?', expects: 'Never. The queue accepts everything, so the pool never has a reason to expand past core — and the queue grows until the heap gives out. This is the single most valuable thing to know about ThreadPoolExecutor.' },
      { q: 'How do you size a pool for IO-bound work?', expects: 'Higher than core count, derived from the wait-to-service ratio, and bounded by the downstream dependency\'s capacity — not an arbitrary large number.' },
      { q: 'What happens to submitted tasks when the JVM shuts down?', expects: 'Non-daemon pool threads keep it alive; without shutdown and awaitTermination you either hang or lose in-flight work.' },
    ],
    systemContext: 'This is the layer directly beneath every async annotation in a framework. A Spring @Async method runs on a pool configured exactly like this — and the framework default is often a SimpleAsyncTaskExecutor that creates a thread per call, which is unbounded concurrency wearing an annotation.',
    related: [
      { to: { roadmap: 'spring', topic: 'async' }, kind: 'implements', why: '@Async is a proxy that submits to an Executor. Everything about pool sizing and rejection here applies unchanged — the annotation hides the pool, it does not replace it.' },
      { to: { roadmap: 'hld', topic: 'concurrency-scaling' }, kind: 'enables', why: 'Per-instance pool capacity is what a system design is estimating when it decides how many instances a throughput target needs.' },
      { to: { roadmap: 'hld', topic: 'backpressure' }, kind: 'implements', why: 'A bounded queue with a rejection policy is backpressure implemented inside one process.' },
      { to: { roadmap: 'java', topic: 'concurrent-collections' }, kind: 'requires', why: 'The pool\'s work queue is a BlockingQueue — its bounding behaviour is the pool\'s bounding behaviour.' },
    ],
    practice: {
      intent: 'Configure a pool badly on purpose, observe the failure mode, then fix it.',
      exercises: [
        { title: 'The pool that never grows', detail: 'Core 2, max 20, unbounded queue. Submit 10,000 slow tasks and log the active thread count. Show it never exceeds 2 while the queue grows without limit.' },
        { title: 'Bound it and choose a policy', detail: 'Swap in an ArrayBlockingQueue of 100. Submit 10,000 tasks under each rejection policy and describe the user-visible difference.' },
        { title: 'Compose without blocking', detail: 'Fetch a user and their orders concurrently with CompletableFuture, combine them, and add a timeout and an exceptionally fallback. No call to get().' },
        { title: 'Size it from evidence', detail: 'Take an IO-bound task with a known service time. Derive a pool size from the wait/service ratio, then measure throughput at half, one and double that size.' },
      ],
    },
  },
  {
    id: 'advanced-streams', roadmap: 'java', tier: 2,
    title: 'Advanced streams and modern Java',
    summary: 'Custom collectors, flatMap, records, sealed types, pattern matching.',
    whyItMatters: 'Modern Java changes how domain models are written. Records and sealed interfaces remove a lot of the boilerplate that LLD answers used to drown in.',
    whatToLearn: [
      'flatMap for nested structures',
      'teeing and custom Collector implementations',
      'Records as transparent data carriers — and what they give you for free',
      'Sealed interfaces plus pattern matching for exhaustive domain modelling',
      'var: where it helps readability and where it hides intent',
    ],
    dependencies: [{ roadmap: 'java', topic: 'streams' }],
    nextSteps: [{ roadmap: 'lld', topic: 'domain-modelling' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Where would a record be the wrong choice?', expects: 'Anything needing mutability, inheritance, or invariants enforced after construction — a JPA entity being the obvious example.' },
    ],
    related: [{ to: { roadmap: 'lld', topic: 'domain-modelling' }, kind: 'enables', why: 'Sealed interfaces plus records make an exhaustive domain model expressible in far less code.' }],
    practice: {
      intent: 'Model a domain with the modern tools.',
      exercises: [
        { title: 'Sealed payment result', detail: 'Model Success | Declined | Pending as a sealed interface of records and handle it with exhaustive pattern matching. Add a fourth case and let the compiler find every switch.' },
      ],
    },
  },
]
