import type { Topic } from '../types'

export const springTopics: Topic[] = [
  {
    id: 'ioc-di', roadmap: 'spring', tier: 1,
    title: 'IoC and dependency injection',
    summary: 'The container owns construction, so your classes declare what they need instead of building it.',
    whyItMatters: 'Everything else in Spring is downstream of this. Testability, swappable implementations and proxying all depend on the container holding the references.',
    whatToLearn: [
      'Inversion of control as a principle, DI as the mechanism',
      'Constructor injection as the default — and why field injection hurts testing',
      'ApplicationContext as the bean registry',
      'Component scanning vs explicit @Bean in @Configuration',
      'Wiring by type, and how @Qualifier resolves ambiguity',
    ],
    dependencies: [{ roadmap: 'java', topic: 'oop' }],
    nextSteps: [{ roadmap: 'spring', topic: 'bean-scopes' }, { roadmap: 'spring', topic: 'rest-api' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Why prefer constructor injection over field injection?', expects: 'Immutability, mandatory dependencies made explicit, and the ability to construct the class in a test without a container.' },
      { q: 'Two beans implement the same interface. What happens?', expects: 'NoUniqueBeanDefinitionException unless disambiguated by @Qualifier, @Primary, or the parameter name.' },
    ],
    systemContext: 'The container is also what makes AOP possible: because Spring hands out the reference, it can hand out a proxy instead of your object.',
    related: [
      { to: { roadmap: 'java', topic: 'oop' }, kind: 'implements', why: 'Programming to an interface, enforced by a container rather than by team discipline.' },
      { to: { roadmap: 'spring', topic: 'transactional-deep' }, kind: 'enables', why: 'Proxy-based transactions only work because the container, not your code, controls the reference.' },
    ],
    practice: {
      intent: 'Build the wiring by hand once so the container stops being magic.',
      exercises: [
        { title: 'Hand-roll a container', detail: 'Write a tiny registry that scans for an annotation, instantiates by constructor, and resolves dependencies by type. Stop when you hit circular dependencies — then explain how Spring handles them.' },
      ],
    },
  },
  {
    id: 'bean-scopes', roadmap: 'spring', tier: 1,
    title: 'Bean scopes and lifecycle',
    summary: 'Singleton by default — and what that means when every request thread shares the instance.',
    whyItMatters: 'The default scope is a shared mutable object across all request threads. Most accidental concurrency bugs in Spring services start here.',
    whatToLearn: [
      'Singleton, prototype, request, session — and when non-singleton is justified',
      'Lifecycle callbacks: @PostConstruct, @PreDestroy',
      'Why singleton beans must be stateless',
      'Injecting a prototype into a singleton, and the trap it creates',
    ],
    dependencies: [{ roadmap: 'spring', topic: 'ioc-di' }],
    nextSteps: [{ roadmap: 'spring', topic: 'transactional-deep' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Is a @Service bean thread-safe?', expects: 'Only if stateless. It is one instance shared by every request thread — an instance field is a data race.' },
      { q: 'You inject a prototype bean into a singleton. How many instances get created?', expects: 'One, at wiring time. Fresh instances need ObjectProvider or a lookup method.' },
    ],
    systemContext: 'A mutable field on a @Service under production traffic is the Spring-shaped version of the shared-counter race from the Java roadmap.',
    related: [{ to: { roadmap: 'java', topic: 'threads-and-safety' }, kind: 'implements', why: 'Singleton scope creates exactly the shared mutable state that topic warns about — the framework makes it invisible.' }],
  },
  {
    id: 'rest-api', roadmap: 'spring', tier: 1,
    title: 'REST APIs and error contracts',
    summary: 'Controllers, DTOs, validation, status codes, and one place where exceptions become responses.',
    whyItMatters: 'Your API is a contract. Leaking entities or returning 200 with an error body are the two failures reviewers catch immediately.',
    whatToLearn: [
      'Controller-Service-Repository, and what belongs in each',
      'DTOs at the boundary — never expose entities',
      'Bean validation with @Valid and meaningful constraint messages',
      '@ControllerAdvice as the single translation point',
      'Status codes that mean something: 400 vs 404 vs 409 vs 422',
    ],
    dependencies: [{ roadmap: 'java', topic: 'exceptions' }, { roadmap: 'spring', topic: 'ioc-di' }],
    nextSteps: [{ roadmap: 'spring', topic: 'jpa-basics' }, { roadmap: 'hld', topic: 'api-design' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'Why not return your JPA entity from a controller?', expects: 'Lazy-loading serialisation failures, accidental field exposure, and a contract that changes whenever the schema does.' },
    ],
    systemContext: 'The error contract is what a calling service builds its retry logic against — a 409 means stop, a 503 means retry.',
    related: [{ to: { roadmap: 'java', topic: 'exceptions' }, kind: 'implements', why: 'Global exception handling is the error-boundary idea applied at the HTTP layer.' }],
    practice: {
      intent: 'Build the boundary end to end.',
      exercises: [
        { title: 'Order endpoint with a real error contract', detail: 'POST /orders with validation, a DTO, and @ControllerAdvice mapping three domain exceptions to distinct status codes. Prove each with a test.' },
      ],
    },
  },
  {
    id: 'jpa-basics', roadmap: 'spring', tier: 1,
    title: 'JPA and Spring Data',
    summary: 'Entities, repositories, relationships, and the fetch decisions that decide your query count.',
    whyItMatters: 'JPA hides SQL well enough that people stop thinking about it. Nearly every slow endpoint in a Spring service is a fetch strategy that was never examined.',
    whatToLearn: [
      'Entity mapping, identity, and the generated-id lifecycle',
      'Repository abstraction and derived query methods',
      'OneToMany / ManyToOne and owning side',
      'Lazy vs eager, and why eager-by-default is a trap',
      '@Transactional at the service layer as the default placement',
    ],
    dependencies: [{ roadmap: 'spring', topic: 'rest-api' }, { roadmap: 'database', topic: 'acid-transactions' }],
    nextSteps: [{ roadmap: 'spring', topic: 'persistence-context' }, { roadmap: 'spring', topic: 'transactional-deep' }],
    howDeep: 'working',
    interviewQuestions: [
      { q: 'What does LazyInitializationException actually tell you?', expects: 'You touched an unloaded association after the persistence context closed — a transaction boundary problem, not a mapping problem.' },
    ],
    related: [
      { to: { roadmap: 'database', topic: 'indexes' }, kind: 'requires', why: 'A derived query method still becomes SQL that either hits an index or scans the table.' },
      { to: { roadmap: 'java', topic: 'equals-hashcode' }, kind: 'requires', why: 'Entities with generated ids have no stable hash code before persist, which breaks any Set holding them.' },
    ],
  },
  {
    id: 'persistence-context', roadmap: 'spring', tier: 2,
    title: 'Persistence context and N+1',
    summary: 'The first-level cache, dirty checking, entity states — and the query explosion they hide.',
    whyItMatters: 'This is the mechanism behind the two most common JPA surprises: an update you never called, and 400 queries where you expected one.',
    whatToLearn: [
      'Entity states: transient, managed, detached, removed',
      'Dirty checking — a managed entity is flushed without an explicit save',
      'First-level cache scope: one persistence context, one transaction',
      'N+1 detection, and fetch join vs entity graph vs projection as the three fixes',
      'When a projection beats an entity entirely',
    ],
    dependencies: [{ roadmap: 'spring', topic: 'jpa-basics' }],
    nextSteps: [{ roadmap: 'spring', topic: 'transactional-deep' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'You changed a managed entity but never called save. Was it persisted?', expects: 'Yes — dirty checking flushes at commit. Whether that is desirable is the follow-up worth having an opinion on.' },
      { q: 'How do you detect N+1 before production does?', expects: 'Log SQL in tests and assert query counts. Reading code is not detection.' },
    ],
    systemContext: 'An endpoint that returns 50 orders each with a lazy customer issues 51 queries. It is invisible in development with 3 rows and fatal at production volume.',
    related: [
      { to: { roadmap: 'database', topic: 'query-execution' }, kind: 'requires', why: 'Fixing N+1 means reading the plan of the joined query — the fix can create a worse problem than the one it solved.' },
      { to: { roadmap: 'database', topic: 'indexes' }, kind: 'requires', why: 'A fetch join without a supporting index turns 51 fast queries into one slow one.' },
    ],
    practice: {
      intent: 'Count queries, do not guess at them.',
      exercises: [
        { title: 'Produce and kill an N+1', detail: 'Build Order → Customer lazily, fetch 50 orders, and log SQL to show 51 queries. Fix with a fetch join, then with a projection, and compare both plans.' },
      ],
    },
  },
  {
    id: 'transactional-deep', roadmap: 'spring', tier: 2,
    title: '@Transactional in depth',
    summary: 'A proxy, a database transaction, and the gap between the annotation and what the database actually does.',
    whyItMatters: 'The annotation is one line, and it sits on top of proxying, isolation, locking and MVCC. Interviewers use it precisely because a shallow answer is obvious and a deep one connects four layers.',
    whatToLearn: [
      'It is a proxy: Spring wraps the bean, and the transaction begins on the proxied call',
      'Self-invocation — an internal call bypasses the proxy entirely and no transaction starts',
      'Propagation: REQUIRED, REQUIRES_NEW, NESTED, and what each means for rollback',
      'Isolation delegates to the database — Spring does not implement it',
      'Rollback rules: unchecked rolls back, checked does not, unless declared',
      'Why a transaction must not span a network call to another service',
    ],
    dependencies: [
      { roadmap: 'spring', topic: 'persistence-context' },
      { roadmap: 'database', topic: 'acid-transactions' },
    ],
    nextSteps: [{ roadmap: 'spring', topic: 'outbox' }, { roadmap: 'database', topic: 'isolation-levels' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'A @Transactional method calls another @Transactional method in the same class. How many transactions?', expects: 'One — the inner call never touches the proxy, so its annotation does nothing. The classic self-invocation question.' },
      { q: 'You set isolation = REPEATABLE_READ. What does Spring do?', expects: 'Passes it to the driver. The behaviour is the database\'s, which is why the same setting behaves differently on PostgreSQL and MySQL.' },
      { q: 'Your method throws a checked exception. Does it roll back?', expects: 'No, not by default — only unchecked and Error, unless rollbackFor says otherwise. A frequent source of half-committed state.' },
      { q: 'Can @Transactional guarantee consistency across a DB write and a Kafka publish?', expects: 'No. Two systems, no shared transaction — the dual-write problem, which is what the outbox pattern exists to solve.' },
    ],
    systemContext: 'In OrderFlow, the order write and the event publish must both happen or neither. @Transactional covers only the database half, which is exactly why the outbox exists in that architecture.',
    related: [
      { to: { roadmap: 'database', topic: 'acid-transactions' }, kind: 'implements', why: 'The annotation is a declarative wrapper over BEGIN/COMMIT/ROLLBACK — knowing the database primitive is knowing what the annotation can and cannot do.' },
      { to: { roadmap: 'database', topic: 'isolation-levels' }, kind: 'requires', why: 'The isolation attribute is delegated straight to the database; its behaviour is defined there, not in Spring.' },
      { to: { roadmap: 'database', topic: 'mvcc' }, kind: 'requires', why: 'On PostgreSQL and Oracle, the isolation you requested is delivered by snapshot visibility rules — MVCC is the mechanism underneath the attribute.' },
      { to: { roadmap: 'spring', topic: 'persistence-context' }, kind: 'requires', why: 'The transaction defines the persistence context\'s lifetime, which is why lazy loading fails once it closes.' },
      { to: { roadmap: 'spring', topic: 'outbox' }, kind: 'enables', why: 'Recognising that a transaction cannot span a broker is what motivates the outbox.' },
      { to: { roadmap: 'hld', topic: 'idempotency' }, kind: 'contrasts', why: 'Where a transaction cannot reach, idempotency is the substitute guarantee — retry safety instead of atomicity.' },
    ],
    practice: {
      intent: 'Reproduce each failure mode, then explain it out loud.',
      exercises: [
        { title: 'Self-invocation, demonstrated', detail: 'Two @Transactional methods in one class, inner called from outer. Throw in the inner one and show the outer did not roll back the way you expected.' },
        { title: 'The checked-exception hole', detail: 'Throw a checked exception mid-method after a write. Show the write committed. Fix with rollbackFor.' },
        { title: 'Dual write, broken', detail: 'Write a row and publish an event in one @Transactional method. Kill the process between commit and publish. Show the inconsistency, then argue for the outbox.' },
      ],
    },
  },
  {
    id: 'async', roadmap: 'spring', tier: 2,
    title: '@Async and task executors',
    summary: 'An annotation over a thread pool — with the same sizing and rejection decisions, now hidden.',
    whyItMatters: 'The default executor behind @Async creates a new thread per invocation. Under load that is unbounded concurrency behind a one-word annotation.',
    whatToLearn: [
      '@Async is proxy-based, so self-invocation bypasses it exactly like @Transactional',
      'The default SimpleAsyncTaskExecutor does not pool — always define your own',
      'Returning CompletableFuture rather than void so failures are observable',
      'Why @Async and @Transactional on the same method do not compose as expected',
      'Propagating request context (MDC, security) across the pool boundary',
    ],
    dependencies: [{ roadmap: 'java', topic: 'executor-service' }, { roadmap: 'spring', topic: 'ioc-di' }],
    nextSteps: [{ roadmap: 'hld', topic: 'concurrency-scaling' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'What executor runs an @Async method by default?', expects: 'SimpleAsyncTaskExecutor — a new thread per call, no pooling, no bound. Naming the failure mode under load is the point.' },
      { q: 'Does the transaction propagate into an @Async method?', expects: 'No. Different thread, different transaction context. The async work runs outside the caller\'s transaction.' },
      { q: 'Your @Async method returns void and throws. Where does the exception go?', expects: 'Nowhere useful — it needs an AsyncUncaughtExceptionHandler, or return CompletableFuture instead.' },
    ],
    systemContext: 'Sending a confirmation email after an order is placed is the canonical use: the request should not wait on SMTP. The pool bound is what stops a mail outage from consuming every thread in the service.',
    related: [
      { to: { roadmap: 'java', topic: 'executor-service' }, kind: 'implements', why: 'The annotation submits to an Executor. Every pool-sizing and rejection decision from that topic applies here, unchanged and less visible.' },
      { to: { roadmap: 'spring', topic: 'transactional-deep' }, kind: 'contrasts', why: 'Both are proxy-based and both break on self-invocation, but transaction context does not cross the thread boundary that @Async introduces.' },
      { to: { roadmap: 'hld', topic: 'concurrency-scaling' }, kind: 'enables', why: 'Per-instance async capacity is an input to how many instances a throughput target requires.' },
    ],
    practice: {
      intent: 'Replace the default executor and prove the difference.',
      exercises: [
        { title: 'Unbounded by default', detail: 'Call an @Async method 5,000 times with the default executor and count live threads. Then define a bounded ThreadPoolTaskExecutor and show the difference.' },
        { title: 'Carry the context', detail: 'Propagate an MDC trace id into an @Async task with a TaskDecorator, and prove it in the logs.' },
      ],
    },
  },
  {
    id: 'outbox', roadmap: 'spring', tier: 2,
    title: 'Transactional outbox and idempotent consumers',
    summary: 'Making a database write and an event publish atomic when no transaction can span both.',
    whyItMatters: 'The dual-write problem is the defining correctness issue in event-driven services, and the outbox is the standard answer. This is where Spring, the database and Kafka meet.',
    whatToLearn: [
      'The dual-write problem: commit then publish can lose events; publish then commit can emit phantoms',
      'Writing state and an outbox row in ONE local transaction',
      'A relay reading the outbox and publishing — at-least-once by construction',
      'Idempotent consumers, because at-least-once means duplicates are guaranteed',
      'Retry, backoff and DLQ as the failure path',
    ],
    dependencies: [{ roadmap: 'spring', topic: 'transactional-deep' }],
    nextSteps: [{ roadmap: 'hld', topic: 'idempotency' }],
    howDeep: 'deep',
    interviewQuestions: [
      { q: 'Why not just publish inside the @Transactional method?', expects: 'The broker call is not part of the database transaction. A crash after commit loses the event; a rollback after publish emits an event for state that does not exist.' },
      { q: 'The outbox gives you at-least-once. What does that force on consumers?', expects: 'Idempotency — a dedupe key or a natural upsert, because the same event will arrive twice.' },
    ],
    systemContext: 'This is the OrderFlow architecture: order state and outbox row in one transaction, a relay publishing to Kafka, consumers deduplicating on event id.',
    related: [
      { to: { roadmap: 'database', topic: 'acid-transactions' }, kind: 'requires', why: 'The whole pattern rests on the local transaction being genuinely atomic across two tables.' },
      { to: { roadmap: 'hld', topic: 'message-queue' }, kind: 'implements', why: 'This is the reliable-publish half of event-driven architecture as drawn in a system design.' },
      { to: { roadmap: 'hld', topic: 'idempotency' }, kind: 'enables', why: 'At-least-once delivery is only safe because consumers are idempotent.' },
    ],
    practice: {
      intent: 'Build the failure, then the fix.',
      exercises: [
        { title: 'Lose an event', detail: 'Commit then publish, kill the process in between, and show state without its event.' },
        { title: 'Outbox relay', detail: 'Write state plus outbox row in one transaction; a scheduled relay publishes and marks sent. Kill it mid-publish and show the event is re-delivered, not lost.' },
        { title: 'Deduplicate', detail: 'Make the consumer idempotent with a processed-events table. Replay the same event ten times and assert one state change.' },
      ],
    },
  },
]
